# Project

The data was gathered by general practitioners during patients' visits with no history of liver cirrhosis or liver transplant. Every patient was measured, and their waist-to-hip ratio (WHR) was calculated. Patients' physical activity and alcohol consumption was self-reported and alcohol consumption was converted to weekly consumption units. Also, sex and age of each patient were recorded. Patients aged 50 to 70 years were included into the sample. After data collection, their future outcomes of liver cirrhosis and liver transplant were observed during a 10-year period.

### Aim
We are interested in the average total effect of weekly alcohol consumption on cirrhosis.

### Dataset (n=1000)
- **age** - patient's age (numerical variable)
- **sex** - patient's sex (categorical variable: "Male"/"Female")
- **physical_activity** - patient's physical activity level (categorical variable: "Low"/"Moderate"/"High")
- **alcohol_units** - alcohol consumption (numerical variable; units per week) 
- **whr** - patient's waist-to-hip ratio (numerical variable)
- **cirrhosis** - binary variable indicating whether the patient was diagnosed with liver cirrhosis within 10 years (0 = no, 1 = yes)
- **liver_transplant** - binary variable indicating whether the patient received a liver transplant within 10 years (0 = no, 1 = yes)

In [6]:
import pandas as pd, numpy as np
# Data
data = pd.read_csv('./simulated_data.csv')
data

,age,sex,physical_activity,alcohol_units,whr,cirrhosis,liver_transplant
0,66,Male,Moderate,8.988626,1.063755,0,0
1,60,Male,Moderate,8.932392,1.058569,0,0
2,52,Female,Moderate,14.657677,0.945773,1,0
3,63,Male,Low,16.057751,1.189715,0,0
4,51,Female,High,0.000000,0.744882,0,0
...,...,...,...,...,...,...,...
995,67,Female,Low,8.457113,1.009681,1,0
996,65,Female,High,6.489836,0.898976,0,0
997,59,Female,Moderate,5.790423,0.885982,0,1
998,56,Female,Moderate,12.957578,0.949604,1,1
999,68,Female,High,6.963678,0.909871,0,0